### ISSUE TITLE
[Docs] Display Activations On Fibers (1.4.0)

### ISSUE THREAD

**Issue by lucasferryinbibo** [Inbibo/adonisfx_docs#127]
# What to do
- [x] Display activation on fibers (muscle section)
- [x] Display activation on fibers (ribbon section)

**Comment by josevalverdeinbibo** [comment]
### FAT
![image](https://github.com/user-attachments/assets/0abe03b3-5df4-4342-bae6-bf8795c9bfe9)

### MUSCLE
![image](https://github.com/user-attachments/assets/29e95351-806c-4d07-833a-13e7c20875a7)
![image](https://github.com/user-attachments/assets/0cae3f0a-82ee-4b05-b099-bfb804804c6d)
![image](https://github.com/user-attachments/assets/1a73849e-d4dc-4c9d-bcf5-e8bb5e77ca29)
![image](https://github.com/user-attachments/assets/99bcaeed-282a-4ee9-aa2a-b95837b92e0b)
![image](https://github.com/user-attachments/assets/94a27c25-4b51-4c88-ad32-809c5e231144)

### RIBBON
![image](https://github.com/user-attachments/assets/f8821579-0662-4a57-b851-a15d0bf6eaaf)
![image](https://github.com/user-attachments/assets/52962945-d73f-4854-8120-eaf79a0f00a0)
![image](https://github.com/user-attachments/assets/f6c9b144-4411-44da-ab37-b5f544c89cee)
![image](https://github.com/user-attachments/assets/1988c93c-bd72-4245-8030-e148912df135)

### SIMSHAPE
![image](https://github.com/user-attachments/assets/b47662c0-c70c-41f9-bfc1-1881c60fbfdd)

### SKIN
![image](https://github.com/user-attachments/assets/646e2444-8de3-4485-825d-a1a419bd979a)
