### ISSUE TITLE
[Docs] Update table of contents: Deformers and Nodes

### ISSUE THREAD

**Issue by josevalverdeinbibo** [Inbibo/adonisfx_docs#149]
- [x] Update table of contents to create 2 subsections: Deformers and Nodes.

**Comment by josevalverdeinbibo** [comment]
This is how the reorganization (Deformers and Nodes) would look like from `mkdocs serve`.

#### Index
![image](https://github.com/user-attachments/assets/df55a035-d0f6-4100-b85a-66363ecc8cf8)

#### Table of contents
![image](https://github.com/user-attachments/assets/792572c7-a69c-4169-9b59-821ae9ec89ae)

NOTE: The deformers and nodes sections seem to be expanded by default in the table of contents.

**Comment by carlosmonteagudoinbibo** [comment]
Moving this issue to on hold until we recieve assistance from defstudio. I will take care of providing any updates and movinb the issue back to in progress
 cc @josevalverdeinbibo

**Comment by carlosmonteagudoinbibo** [comment]
03/dic

DefStudio has updated the parser to fully match our needs to be able to use relative links (e.g. `../images/adn_fat.png`).
We are now in the position to complete this issue and update the documentation.
Moving this issue back to in progress.
cc @josevalverdeinbibo
