### ISSUE TITLE
[Docs] Basic requirements for Adonis Documentation

### ISSUE THREAD

**Issue by carlosmonteagudoinbibo** [Inbibo/adonisfx_docs#2]
Definition of Done:

- [x] Define a new structure to support versioning
- [x] Introduction
- [x] Terminology
- [x] Installation
- [x] Licensing (Missing CentOS)
- [x] System Requirements
- [x] Release notes
- [x] Update screenshots affected by the new icons

**Comment by carlosmonteagudoinbibo** [comment]
> I will leave a comment here with the pending topics to discuss regarding the "Licensing" section for AdonisFX:
> 
> * Do we explain "deactivation" for all methods or just refer to the LimeLM docs?
> * Should we add a FAQ page like Ragdoll Dynamics does? https://learn.ragdolldynamics.com/licencing/
> * I've noticed that we are providing several .exe files for activating off-line interactive and batch licenses. However we are not providing anything for deactivating. Should we just explain the analogy in commands or refer to the LimeLM docs?
> * Do we want a troubleshooting section and FAQ also for floating licensing?
> * Should we add some structure to how the client should contact with support to request and Activation Response?

In order:

- Yes, for the floating server case (I mean, when it's via TurboFloatServer.exe). We are not providing executables to deactivate Node-Locked licenses. I would suggest to add a note for those cases saying something like: if you need to deactivate your machine, please contact support
- I would add those questions that you think are interesting to the FAQ page, not the Licensing.
- I don't understand "the analogy in commands". I think my reply to first question applies to this one as well.
- I think my reply to second question does apply to this one as well. No trouble shooting I think, but feel free to add as many questions to FAQ as you want
- Good question. We don't really need much info apart from the request file, but you can ask to specify the username in Inbibo website and the date of the request generation.

**Comment by lucasferryinbibo** [comment]
> * if you need to deactivate your machine, please contact support

Everything addressed except for the FAQs. I will elaborate that list shortly
