### ISSUE TITLE
[Docs] Section "abstract Activation Modes" is not rendered properly in Preview Tool

### ISSUE THREAD

**Issue by carlosmonteagudoinbibo** [Inbibo/adonisfx_docs#38]
In branch `#35-docs-finalReviewAndPolishing` for issue #35 we have some issues with a section tagged as `abstract "Activation Modes"`
This structure was working fine with the "material" theme from mkdocs-material, but it's not with "readthedocs" anymore. 

![image](https://github.com/Inbibo/adonisfx_docs/assets/95488269/1755a25e-4798-46cd-a2a1-c09a6bc81069)
![image](https://github.com/Inbibo/adonisfx_docs/assets/95488269/14f7738f-ca43-4f1b-879b-4d167dfbe6fb)

This issue aims to define a new way of writing something similar (not necessarily a table with tabs) to this (example with mkdocs-material theme):
![image](https://github.com/Inbibo/adonisfx_docs/assets/95488269/3baf67ec-5f73-42dd-b502-4e068c6c823d)

**Comment by fabio-ivona** [comment]
@carlosmonteagudoinbibo we managed to handle something similar to the tabbed note using this syntax:

```
> [!NOTE = Activation Modes]
> === Muscle Patches
> The data in the Adonis Muscle Patches (AMP) file in combination with the deformation status of the Deform Mesh are used to calculate the amount of activation at each vertex. The AMP file is the result of a Machine Learning process and can be generated following [generate muscle patches section](#generate-muscle-patches).
>
> #####Requirements
>  - **Adonis Muscle Patches**.
>  - **Deform mesh**.
>
>  === Plug Values
> The plug values from the Activation List array attribute are used to drive the level of activation at each vertex.
>
> > [!NOTE]
> > - The values must be provided in the range 0 to 1, where 0.0 is no activation and 1.0 is maximum activation.
> > - The values outside of the valid range will be clamped.
>
> === Tab Header 3
> tab 3 content here
```

would you mind to try it and tell me if everything works correctly?

**Comment by fabio-ivona** [comment]
Only thing we can't handle: notes inside notes, nesting is not supported

**Comment by fabio-ivona** [comment]
:+1:  this is in our backlog, we'll fix it soon

**Comment by carlosmonteagudoinbibo** [comment]
Hi @fabio-ivona , is there an issue in your repository linked to that request (fixed width of that table) that we can link here in order to keep track of the progress/resolution?

**Comment by fabio-ivona** [comment]
> Hi @fabio-ivona , is there an issue in your repository linked to that request (fixed width of that table) that we can link here in order to keep track of the progress/resolution?

done

**Comment by carlosmonteagudoinbibo** [comment]
Confirmed in the preview, awesome! Thank you very much. @fabio-ivona
