### ISSUE TITLE
[Docs] Preview tool not refreshing the content properly

### ISSUE THREAD

**Issue by carlosmonteagudoinbibo** [Inbibo/adonisfx_docs#39]
In branch `#35-docs-finalReviewAndPolishing` for issue #35 we see some differences on Github that we don't through the Preview tool. 

![image](https://github.com/Inbibo/adonisfx_docs/assets/95488269/f746d620-c6af-4907-b0bf-9deba1fbeec2)

The changes are pushed as it can be seen in the PR: https://github.com/Inbibo/adonisfx_docs/pull/36/files#diff-ed81fb1ff1993a8f977cc684c978aea8ccacf79c11d776b9ee79490fc087fda7R94

**Comment by fabio-ivona** [comment]
fixed 
![image](https://github.com/Inbibo/adonisfx_docs/assets/8792274/783aab66-24ab-4fbf-ae7b-708674eb029c)

**Comment by carlosmonteagudoinbibo** [comment]
Thanks! Closing this issue
