### ISSUE TITLE
[Bug] Notes not rendered properly

### ISSUE THREAD

**Issue by carlosmonteagudoinbibo** [Inbibo/adonisfx_docs#41]
The following lines do not render properly in the preview tool:

- requirements.md
![image](https://github.com/Inbibo/adonisfx_docs/assets/95488269/fa0e096e-1422-4309-b54b-a668260df583)

- edge evaluator
![image](https://github.com/Inbibo/adonisfx_docs/assets/95488269/f229b4d9-8f4e-48e5-9429-59bf271abec7)

- skin
![image](https://github.com/Inbibo/adonisfx_docs/assets/95488269/1c81b487-ddca-4572-a350-a3c37511ba18)

**Comment by fabio-ivona** [comment]
@carlosmonteagudoinbibo would you mind to open an issue in our repository?

https://github.com/defstudio/inbibo/issues

**Comment by carlosmonteagudoinbibo** [comment]
@fabio-ivona issue created: https://github.com/defstudio/inbibo/issues/345
Please, let me know if you need more information.
The other two notes in edge_evaluator and skin are rendered properly. Thanks.
I will keep this issue open until the one in your repository is closed.

**Comment by carlosmonteagudoinbibo** [comment]
Fixed. The issue in defstudio repository is completed and closed
