### ISSUE TITLE
[Docs] Release v1.1.0 Shape Preservation

### ISSUE THREAD

**Issue by carlosmonteagudoinbibo** [Inbibo/adonisfx_docs#71]
Definition of Done:

- [x] AdnMuscle
   - [x] Add attributes
     - [x] Screenshots
   - [x] Update AETemplate
   - [x] Update Painted Weights
     - [x] Screenshots
   - [x] Debugger
     - [x] Screenshots
- [x] AdnRibbonMuscle
   - [x] Add attributes
     - [x] Screenshots
   - [x] Update AETemplate
   - [x] Update Painted Weights
     - [x] Screenshots
   - [x] Debugger
     - [ ] Screenshots
- [x] AdnSkin
   - [x] Add attributes
     - [x] Screenshots
   - [x] Update AETemplate
   - [x] Update Painted Weights
     - [x] Screenshots
   - [x] Debugger
     - [x] Screenshots
- [x] AdnSimshape
   - [x] Add attributes
     - [x] Screenshots
   - [x] Update AETemplate
   - [x] Update Painted Weights
     - [x] Screenshots
   - [x] Debugger
     - [x] Screenshots

**Comment by lucasferryinbibo** [comment]
Let me write here the overall changes that affects parameters being exposed to the final user. This applies to all deformers equally:
- Added `Shape Preservation` paintable attribute entry to the paint tool. 0.0 for Skin and Simshape and 0.1 for Muscle and Ribbon Muscle as defaults.
- Added "Override Shape Preserve Stiffness" as attribute `.overrideShapePreservationStiffness` to the UI. If the option is disabled the system will use the solver stiffness value either from the Material or the Stiffness value. If enabled it will use the stiffness exposed in "Shape Preserve Stiffness".
- Added "Shape Preserve Stiffness" as attribute `.stiffnessShapePreservation` to the UI. This option will only be active when the user selects "Override Shape Preserve Stiffness" as `.overrideShapePreservationStiffness` attribute in the UI.
- If the stiffness value of "Shape Preserve Stiffness" is 0.0 then the constraint projection will be skipped.
- Also check the debugger which for the triangle creates an edge between the 1st and the 3rd vertex.

Be aware that the Shape Preservation PR also reordered the entries in the paint tool and the debugger for all deformers so we have to attach new screenshots. That is also true for Collision Constraints being renamed to Slide Collision Constraints for example.
