### ISSUE TITLE
[Docs] Stiffness per constraint type

### ISSUE THREAD

**Issue by josevalverdeinbibo** [Inbibo/adonisfx_docs#97]
Definition of Done:

- [x] Update the attribute editor template screenshots showing the "Stiffness Settings" section.
    - attribute_editor_part_two_muscle.png
    - attribute_editor_part_two_ribbon.png
    - attribute_editor_part_two_simshape.png
    - attribute_editor_part_two_skin.png
- [x] Modify the attribute tables for all deformers to include the new stiffness attributes.
- [x] Add a note mentioning the attributes deprecated and the behaviour when the checkbox is enabled.

**Comment by lucasferryinbibo** [comment]
I was reading through the docs. Could you fix these typos in this PR please? thanks! (In Licensing section)
![image](https://github.com/user-attachments/assets/d9ab08c5-b211-452e-b2a7-8e50085c7512)

**Comment by lucasferryinbibo** [comment]
This issue was not formally closed as we are waiting for final approval from @carlosmonteagudoinbibo and to align with the final decisions made whe we closed the original development task
